### PR TITLE
Milestone 6

### PR DESCRIPTION
**Pull request by RoyNyaga**

### CODE REVIEW

**Comment by RoyNyaga** [comment]
Please any idea on how to implement this, I don't know where to start, it
could be an article or any good information.

**Comment by adriaanbd** [comment]
You could have a callback that creates a second friendship record with the user id’s inverted. Once you confirm a friendship, the other record would also be updated. This would solve the issue.

**Comment by RoyNyaga** [comment]
Sorry for disturbing a lot I wish to be clear about something,
preventing same records from being saved in the database can be done from
Model validations which will include a constraint in the database but
preventing a user from sending a friend request to another user who
previously sent him a friend request can only be done at the level of the
controller, meaning that it can be stopped for users using the application
but for someone using the console, there will be no rollback and thus it
can't be stopped. I wish to know if it's possible to enforce such a
constraint at the level of the database or model.

**Comment by RoyNyaga** [comment]
Because I created a callback function to save the reverse of an
initial frenship request and through the web i could not send a friend
request to a user who previously sent me a friend request but that was not
the case in the console.

**Comment by RoyNyaga** [comment]
Included uniqueness constraints in the friendship model and restricted users from sending a friend request to other users who previously sent then a friend request.

**Comment by RoyNyaga** [comment]
Thanks Raphael

**Pull request merged**
